micronaut.application.name = 'micronautData'
netty.default.allocator.max-order = 3
jpa.default.properties.hibernate.hbm2ddl.auto = 'none'

[datasources.default]
driverClassName = 'org.postgresql.Driver'
db-type = 'postgresql'
schema-generate = 'CREATE_DROP'
dialect = 'POSTGRES'
